const navMenu = [
	{
		index:"1",
		name:"门店管理",
		icon:"el-icon-menu",
		sub:[
			{index:"1-1",name:"门店信息",routerName:"shopInfo",icon:"el-icon-plus"},
			{index:"1-2",name:"门店列表",routerName:"shopList",icon:"el-icon-plus"},
			{index:"1-3",name:"门店类别",routerName:"shopType",icon:"el-icon-plus"},
			{index:"1-4",name:"员工管理",routerName:"empMgr",icon:"el-icon-plus"}
		]
	},
	{
		index:"2",
		name:"商品管理",
		icon:"el-icon-goods",
		sub:[
			{index:"2-1",name:"商品列表",routerName:"goodsList",icon:"el-icon-tickets"},
			{index:"2-2",name:"商品类别",routerName:"goodsType",icon:"el-icon-plus"},
			{index:"2-3",name:"商品规格",routerName:"goodsSpec",icon:"el-icon-plus"}
		]
	},
	{
		index:"3",
		name:"会员特权",
		icon:"el-icon-star-on",
		sub:[
			{index:"3-1",name:"会员列表",routerName:"memberList",icon:"el-icon-tickets"},
			{index:"3-2",name:"会员等级",routerName:"memberLevel",icon:"el-icon-tickets"}
		]
	},
	{
		index:"4",
		name:"收银管理",
		icon:"el-icon-mobile-phone",
		sub:[
			{index:"4-1",name:"收银台",routerName:"cashierDesk",icon:"el-icon-tickets"},
			{index:"4-2",name:"收银单",routerName:"ticket",icon:"el-icon-tickets"}
		]
	},
	{
		index:"5",
		name:"采购管理",
		icon:"el-icon-phone",
		sub:[
			{index:"5-1",name:"供应商列表",routerName:"providerList",icon:"el-icon-tickets"},
			{index:"5-2",name:"采购订单",routerName:"orderList",icon:"el-icon-tickets"},
			{index:"5-3",name:"采购收货单",routerName:"invoiceList",icon:"el-icon-tickets"},
			{index:"5-4",name:"采购退货单",routerName:"rollbackList",icon:"el-icon-tickets"},
		]
	},
	{
		index:"6",
		name:"批发管理",
		icon:"el-icon-phone-outline",
		sub:[
			{index:"6-1",name:"客户列表",routerName:"customerList",icon:"el-icon-tickets"},
			{index:"6-2",name:"批发订单",routerName:"wholeOrderList",icon:"el-icon-tickets"},
			{index:"6-3",name:"批发出库单",routerName:"wholeInvoiceList",icon:"el-icon-tickets"},
			{index:"6-4",name:"批发退货单",routerName:"wholeRollbackList",icon:"el-icon-tickets"},
		]
	},
	{
		index:"7",
		name:"仓库管理",
		icon:"el-icon-edit-outline",
		sub:[
			{index:"7-1",name:"仓库列表",routerName:"storeList",icon:"el-icon-tickets"},
			{index:"7-2",name:"库存盘点",routerName:"inventoryCheck",icon:"el-icon-tickets"},
			// {index:"7-3",name:"调拨出库单",routerName:"wholeList",icon:"el-icon-tickets"},
			// {index:"7-4",name:"调拨入库单",routerName:"wholeRollbackList",icon:"el-icon-tickets"},
		]
	},
	{
		index:"8",
		name:"报表管理",
		icon:"el-icon-document",
		sub:[
			{index:"8-1",name:"收银信息记录",routerName:"shouyin",icon:"el-icon-tickets"},
		]
	}
]

export default navMenu
